#!/usr/bin/env bash
#displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=: read -r user password uid gid name home shell
do
  echo "The user $user is part of the $gid gang, lives in $home and rides $shell.
  USER ID's place is protected by the passcode $password, more info about the user here: $name"
done < /etc/passwd
