#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59

hr=0
min=1
while [ $hr -ne 13 ]; do
  echo "Hour: $hr"
  hr=$((hr+1))
  while [ $min -ne 60 ]; do
    echo $min
    min=$((min+1))
  done
  min=1
done
